- set_fact: 
    network_config:
      name: "{{ vlan }}"       
      type: "static"
      ip: "{{ item.ip | ipaddr('address') }}"
      netmask: "{{ item.ip | ipaddr('netmask')}}"
      gateway: "{{ item.ip | ipaddr('1') | ipaddr('address') }}"
      dns_servers: "{{ dns_nameservers }}"
      start_connected: true
  with_items: "{{ nodefacts }}"
 # when: network_type == 'static'