---
- name: Unarchive node exporter installer
  copy:
    src: node_exporter
    dest: /usr/local/bin
    mode: 766
    #remote_src: yes

- name: create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false

- name: Create node exporter systemd unit
  template: 
    src: prometheussystemd.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start/enable node exporter
  systemd: 
    name: node_exporter.service
    state: restarted
    enabled: true
    daemon_reload: yes