---
- hosts: localhost
  gather_facts: False

  tasks: 

    - name: Remove GitLab project
      community.general.gitlab_project:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        name: "{{ gitlabprojectname }}"
        group: "{{ company }}"
        state: absent