- set_fact: 
    network_config:
      name: "{{ vlan }}"       
      type: "static"
      ip: "{{ controlplanefacts.ip | ipaddr('address') }}"
      netmask: "{{ controlplanefacts.ip | ipaddr('netmask')}}"
      gateway: "{{ controlplanefacts.ip | ipaddr('1') | ipaddr('address') }}"
      dns_servers: "{{ dns_nameservers }}"
      start_connected: true
 # when: network_type == 'static'