---
---
- set_fact: 
    network_config:
      name: "{{ vlan }}"
      type: "{{ network_type }}"
      start_connected: true
  when: network_type == 'dhcp'
        
- set_fact: 
    network_config:
      name: "{{ vlan }}"       
      type: "{{ network_type }}"
      ip: "{{ ip | ipaddr('address') }}"
      netmask: "{{ ip | ipaddr('netmask')}}"
      gateway: "{{ ip | ipaddr('1') | ipaddr('address') }}"
      dns_servers: "{{ dns_nameservers }}"
      start_connected: true
  when: network_type != 'dhcp'