--- 
- hosts: localhost
  gather_facts: false
  vars: 
  
  tasks: 


    - name: Create control plane inventory
      tower_inventory:
        name: "{{ clusterfacts.id }}"
        organization: Default
        state: present
        variables: 
    
    
    - name: Add controlplane
      tower_host:
        name: "{{ clusterfacts.id }}"
        inventory: "ControlPlanes"
        state: present
        variables:
          controlplane:
            - ip: "{{ controlplanefacts.ip }}"
              hostname:  "{{ controlplanefacts.hostname }}"
          subnet: "{{ controlplanefacts.subnet }}"
          nodeip: "{% for node in nodefacts %}{{ node.ip }}\n{% endfor %}"
          nodehostnames: "{% for node in nodefacts %}{{ node.hostname }}\n{% endfor %}"
          snatip: "{{ snatfacts.ip }}"
          vlan: "{{ vlan  }}"
          portgroup: "{{ vlan }}"
          clusterid: "{{ clusterfacts.id }}"
          company: "{{ company }}"
          stage: "{{ stage }}"
          vlanid: "{{ controlplanefacts.vlan }}"
          gitlabproject: "{{ gitlab.gitlabproject }}"
          dnsrecordid: "{{ dnsrecordid }}"
      delegate_to: localhost