- hosts: localhost
  gather_facts: false

  tasks: 

    - name: Include role for generating Control plane
      include_role: 
        name: "nodedeployment"




- name: Configure Control Plane
  hosts: new
  gather_facts: true
  become: yes

  tasks:

    - include_vars: enabledtasks.yml

    - name: Include {{ node_tasks | length }} role(s) for node
      include_role:
        name: "nodedeployment"
        tasks_from: "{{ includedtasks }}.yml"
      with_items: "{{ node_tasks }}"
      loop_control: 
        loop_var: includedtasks        