---
- hosts: all
  gather_facts: False
  become: yes

  tasks: 

  - name: Create load balance config file path
    file: 
      path: "/etc/nginx/conf.d/{{ company }}"
      state: directory

  - name: Add load balancer config file
    template: 
      src: "templates/lbconfig.j2"
      dest: "/etc/nginx/conf.d/{{ company }}/{{ clusterfacts.id }}.conf"

  - name: Start/enable systemd service
    systemd: 
      name: nginx.service
      state: restarted
      enabled: true
      daemon_reload: yes